apiVersion : apps/v1
kind: Deployment
metadata:
  name: weightapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weightapp
  template:
    metadata:
      labels:
        app: weightapp
    spec:
      containers:
        - name: weightapp
          image: ben1214test.azurecr.io/weightapprepo
          imagePullPolicy: "Always"
          ports:
          - containerPort: 8080
          envFrom:
          - secretRef:
             name: secret.yml